domain/models/grailed_cards_model.py
from ..config.db import mongo
from ..tools.ptcg_sdk import get_card_from_set

db = mongo.db


class GrailedCardsModel:
    def get_all_cards(self) -> list:
        """
        Returns all documents found within the database's grailed_cards collection
        """
        print(f"Getting all grailed cards.")
        return [document for document in db["grailed_cards"].find({})]

    def get_card(self, card_id) -> object:
        """
        Returns the document specified at 'card_id' in the database's grailed_cards collection
        """
        if db["grailed_cards"].find_one({"card_id": card_id}):
            print(f"Card: {card_id} found!")
            return db["grailed_cards"].find_one({"card_id": card_id})
        else:
            print(f"Card: {card_id} not found")
            return None 

    def add_card(self, card_id):
        """
        Adds a new card to the database's grailed_cards collection
        """
        if self.get_card(card_id) is None:
            card_obj = get_card_from_set(card_id)
            formatted_card_obj = {
                "card_id": card_obj[0].id,
                "card_name": card_obj[0].name,
                "card_image": card_obj[0].images.small,
                "prices": self.get_price_data(card_obj[0])
            }
            db["grailed_cards"].insert_one(formatted_card_obj)
            print(f"Added {card_id} to grailed_cards database.")
        else:
            print(f"Cannot add to grailed_cards database: {card_id} already exists.")

    def remove_card(self, card_id):
        """
        Removes a card from the database's grailed_cards collection
        """
        if self.get_card(card_id) is not None:
            print(f"Removing {card_id} from grailed_cards database.")
            db["grailed_cards"].delete_one({"card_id": card_id})
        else:
            print(f"Cannot remove card from grailed_cards database: {card_id} does not exist.")
    
    def get_price_data(self, card_obj):
        prices = {
            "normal": card_obj.tcgplayer.prices.normal,
            "holofoil": card_obj.tcgplayer.prices.holofoil,
            "reverseHolofoil": card_obj.tcgplayer.prices.reverseHolofoil,
            "firstEditionHolofoil": card_obj.tcgplayer.prices.firstEditionHolofoil,
            "firstEditionNormal":card_obj.tcgplayer.prices.firstEditionNormal
        }
        relevant_prices = {}

        for card_type, price in prices.items():
            if price is not None:
                relevant_prices[card_type] = price.market
        
        return relevant_prices


        

domain/models/owned_cards_model.py
from ..config.db import mongo
from ..tools.ptcg_sdk import get_card_from_set

db = mongo.db


class OwnedCardsModel:
    def get_all_cards(self) -> list:
        """
        Returns all documents found within the database's owned_cards collection
        """
        print(f"Getting all owned cards.")
        return [document for document in db["owned_cards"].find({})]

    def get_card(self, card_id) -> object:
        """
        Returns the document specified at 'card_id' in the database's owned_cards collection
        """
        if db["owned_cards"].find_one({"card_id": card_id}):
            print(f"Card: {card_id} found!")
            return db["owned_cards"].find_one({"card_id": card_id})
        else:
            print(f"Card: {card_id} not found")
            return None

    def add_card(self, card_id):
        """
        Adds a new card to the database's owned_cards collection
        """
        if self.get_card(card_id) is None:
            card_obj = get_card_from_set(card_id)
            formatted_card_obj = {
                "card_id": card_obj[0].id,
                "card_name": card_obj[0].name,
                "card_image": card_obj[0].images.small,
                "prices": self.get_price_data(card_obj[0])
            }
            db["owned_cards"].insert_one(formatted_card_obj)
            print(f"Added {card_id} to owned_cards database.")
        else:
            print(f"Cannot add to owned_cards database: {card_id} already exists.")

    def remove_card(self, card_id):
        """
        Removes a card from the database's owned_cards collection
        """
        if self.get_card(card_id) is not None:
            print(f"Removing {card_id} from owned_cards database.")
            db["owned_cards"].delete_one({"card_id": card_id})
        else:
            print(
                f"Cannot remove card from owned_cards database: {card_id} does not exist."
            )

    def get_price_data(self, card_obj):
        prices = {
            "normal": card_obj.tcgplayer.prices.normal,
            "holofoil": card_obj.tcgplayer.prices.holofoil,
            "reverseHolofoil": card_obj.tcgplayer.prices.reverseHolofoil,
            "firstEditionHolofoil": card_obj.tcgplayer.prices.firstEditionHolofoil,
            "firstEditionNormal":card_obj.tcgplayer.prices.firstEditionNormal
        }
        relevant_prices = {}

        for card_type, price in prices.items():
            if price is not None:
                relevant_prices[card_type] = price.market
        
        return relevant_prices

domain/__init__.py
from flask import Flask


def create_app():
    # Flask Config
    app = Flask(__name__)
    app.config.from_pyfile("config/config.py")

    # Startup Config
    from .tools.ptcg_sdk import organized_master_set

    app.master_set = organized_master_set()

    # Database Config
    from .config.db import mongo

    mongo.init_app(app)

    # Register Blueprints
    from .routes.home_blueprint import home_route
    from .routes.sets_blueprint import set_views
    from .routes.grailed_blueprint import grailed_views

    app.register_blueprint(home_route)
    app.register_blueprint(set_views)
    app.register_blueprint(grailed_views)

    return app

domain/routes/grailed_blueprint.py
from flask import Blueprint, render_template, current_app
from domain.tools import ptcg_sdk

grailed_views = Blueprint("grailed_views", __name__)

@grailed_views.route("/grailed")
def all_grails():
    return render_template("grailed.html")

domain/routes/home_blueprint.py
from flask import Blueprint, render_template, current_app
from ..models.grailed_cards_model import GrailedCardsModel

home_route = Blueprint("home_route", __name__)

grailed_model = GrailedCardsModel()


@home_route.route("/")
def home():
    print("LOOK HERE")
    t = grailed_model.get_all_cards()
    print(t[0]["prices"])
    return render_template(
        "home.html",
        master_set=current_app.master_set,
        grailed_data=grailed_model.get_all_cards(),
    )

domain/routes/sets_blueprint.py
from flask import Blueprint, render_template, request, current_app
from ..models.grailed_cards_model import GrailedCardsModel
from ..models.owned_cards_model import OwnedCardsModel

set_views = Blueprint("set_views", __name__)
grailed_model = GrailedCardsModel()
owned_model = OwnedCardsModel()


@set_views.route("/all_sets")
def all_sets():
    return render_template("all_sets.html", master_set=current_app.master_set)


@set_views.route("/all_sets/<string:id>")
def specific_set(id):
    grailed_data = [card_obj["card_id"] for card_obj in grailed_model.get_all_cards()]
    owned_data = [card_obj["card_id"] for card_obj in owned_model.get_all_cards()]
    return render_template(
        "specific_set.html",
        set_data=current_app.master_set[id],
        set_cards=current_app.master_set[id]["set_cards"](id),
        grailed_cards=grailed_data,
        owned_cards=owned_data,
    )


# ---------------------------------------------------------------------------------------------
@set_views.route("/update_db", methods=["POST"])
def update_db():
    card_id = request.form["card_id"]
    card_status = request.form["status"]

    if card_status == "owned":
        owned_model.add_card(card_id)
    elif card_status == "not-owned":
        owned_model.remove_card(card_id)
    elif card_status == "grailed":
        grailed_model.add_card(card_id)

    return "testing"

domain/templates/all_sets.html
{% extends "base.html" %} {% block title %} Sets {% endblock %} {% block
content%}
<div class="container-fluid vh-100">
	<h2 class="text-center text-white py-4 fs-1">Sets 📜</h2>

	<div id="all-sets-container" class="px-4 overflow-auto" style="height: 87%">
		<div class="container text-center pt-4">
			<input
				type="search"
				id="searchbar"
				class="form-control w-75 mx-auto"
				placeholder="Search for sets..."
				aria-label="Search"
			/>
		</div>

		<div class="d-flex flex-wrap justify-content-center overflow-auto">
			{% for set_id in master_set %}
			<div
				id="{{master_set[set_id]['set_name']}}"
				class="
					flex-grow-1
					card
					text-center
					w-25
					h-25
					mx-2
					my-5
					set-or-card-badge set-link
					text-white
					bg-dark
					fs-5
				"
			>
				<a
					class="link-light text-decoration-none"
					href="{{  url_for('set_views.specific_set', id=set_id)  }}"
				>
					<div class="card-header">
						{{ master_set[set_id]['set_name'] }}
					</div>
					<div class="container my-3" style="height: 140px">
						<img
							src="{{ master_set[set_id]['set_logo'] }}"
							alt="Fusion Strike"
							class="card-img-top"
							style="object-fit: contain; height: 100%"
						/>
					</div>

					<div class="card-footer">
						<div class="progress">
							<div
								class="progress-bar bg-danger"
								role="progressbar"
								style="width: 25%"
								aria-valuenow="0"
								aria-valuemin="0"
								aria-valuemax="100"
							>
								0 / {{ master_set[set_id]["set_count"] }}
							</div>
						</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

domain/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
			crossorigin="anonymous"
		/>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
			rel="stylesheet"
		/>
		<link rel="stylesheet" href="../static/styles/style.css" />
		<title>{% block title %} Home {% endblock %}</title>
	</head>
	<body>
		<!--  HEADER START  -->
		<header class="p-5 text-center bg-image">
			<div
				class="d-flex justify-content-center align-items-center h-100 flex-column"
			>
				<h1 class="mb-3 text-white">EEVEE</h1>
				<nav
					class="navbar navbar-expand-lg navbar-light"
					style="background-color: transparent"
				>
					<div class="container-fluid">
						<div class="navbar-nav">
							<a
								href="{{  url_for('home_route.home')  }}"
								class="btn btn-secondary me-2 active"
								>Home</a
							>
							<a
								href="{{  url_for('set_views.all_sets')  }}"
								class="btn btn-secondary me-2 active"
								>Sets</a
							>
							<a
								href="{{  url_for('grailed_views.all_grails')  }}"
								class="btn btn-secondary me-2 active"
								>Grailed</a
							>
						</div>
					</div>
				</nav>
			</div>
		</header>
		<!--  HEADER END  -->

		<!--  CONTENT START (OVERRIDE)  -->
		<div class="container-fluid d-flex h-100">
			{% block content %} {% endblock %}

			<!--  TWITTER FEED START  -->
			<div id="twitter-feed-container" class="container w-25 mt-5">
				<section
					id="twitter-feed-wrapper"
					class="px-5 py-4 text-center"
				>
					<h2 class="text-white pb-1">News 📰</h2>
					<a
						class="twitter-timeline"
						data-theme="dark"
						data-height="97%"
						href="https://twitter.com/pokebeach?ref_src=twsrc%5Etfw"
						>Tweets by pokebeach</a
					>
					<script
						async
						src="https://platform.twitter.com/widgets.js"
						charset="utf-8"
					></script>
				</section>
			</div>
		</div>
		<!--  CONTENT END (OVERRIDE)  -->

		<!--  FOOTER START  -->
		<footer
			class="p-5 text-center justify-content-center align-items-center bg-image"
		>
			<div>
				<div>Footer</div>
			</div>
		</footer>
		<!--  FOOTER END  -->

		<!--  SCRIPTS START  -->
		<script
			src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
			integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
			integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
			crossorigin="anonymous"
		></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="../static/js/searchbar.js"></script>
		<script src="../static//js/set_button_functionality.js"></script>
		<!--  SCRIPTS END  -->
	</body>
</html>

domain/templates/home.html
{% extends "base.html" %} {% block title %} Home {% endblock %} {% block content
%}

<div class="container w-75">
	<!--  GRAILED START  -->
	<section
		id="home-grailed-section-container"
		class="container-fluid my-5 text-center"
	>
		<div class="container h-100">
			<h2 class="text-white pt-4">Grailed 👑</h2>

			{% if grailed_data|length == 0 %}
			<div class="text-white fs-1 text-center text-lg-center h-100">
				NO GRAILED CARDS FOUND 😔
			</div>
			{% else %}
			<div class="d-flex flex-nowrap overflow-auto">
				{% for i in range(0, grailed_data|length) %}
				<div
					class="card text-white bg-dark mx-4 my-4 flex-grow-0 flex-shrink-0 align-items-center w-25 h-25"
				>
					<div class="card-header">
						{{ grailed_data[i]["card_name"] }}
					</div>
					<img
						src='{{ grailed_data[i]["card_image"] }}'
						alt="{{ grailed_data[i]['card_name'] }}"
						class="card-img-top"
					/>
					<div class="card-footer text-success display-6">
						<span>{{ grailed_data[i]["prices"]["holofoil"] }}</span>
					</div>
				</div>
				{% endfor %}
			</div>
			{% endif %}
		</div>
	</section>

	<!--  SET COMPLETION START  -->
	<section
		id="home-master-set-list"
		class="container mb-5 text-center overflow-auto"
		style="height: 500px"
	>
		<h2 class="text-white py-4">Sets 📜</h2>
		<input
			type="search"
			id="searchbar"
			class="form-control w-75 mx-auto"
			placeholder="Search for sets..."
			aria-label="Search"
		/>
		<div class="container-fluid d-flex flex-wrap justify-content-center">
			{% for set_id in master_set %}
			<div
				id="{{ master_set[set_id]['set_name'] }}"
				class="card flex-grow-1 set-or-card-badge set-link text-white text-center bg-dark fs-5 w-25 h-25 mx-2 my-5"
			>
				<a
					class="link-light text-decoration-none"
					href="{{  url_for('set_views.specific_set', id=set_id )  }}"
				>
					<div class="card-header">
						{{ master_set[set_id]["set_name"] }}
					</div>
					<div class="container my-3" style="height: 140px">
						<img
							src="{{ master_set[set_id]['set_logo'] }}"
							alt="Set Logo"
							class="card-img-top"
							style="object-fit: contain; height: 100%"
						/>
					</div>

					<div class="card-footer">
						<div class="progress">
							<div
								class="progress-bar bg-danger"
								role="progressbar"
								style="width: 25%"
								aria-valuenow="0"
								aria-valuemin="0"
								aria-valuemax="100"
							>
								0 / {{ master_set[set_id]["set_count"] }}
							</div>
						</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>
</div>

{% endblock %}

domain/templates/specific_set.html
{% extends "base.html" %} {% block title %} Set {% endblock %} {% block content
%}
<div class="container-fluid vh-100">
	<h2 id="set-title" class="text-white pt-4 text-center fs-1 py-4">
		{{ set_data["set_name"] }}
		<img id="set-symbol" src='{{set_data["set_symbol"]}}' alt="" />
	</h2>

	<div id="specific-set-container" class="overflow-auto" style="height: 87%">
		<div class="container">
			<input
				type="search"
				id="searchbar"
				class="form-control w-75 mx-auto mt-5"
				placeholder="Search for sets..."
				aria-label="Search"
			/>
		</div>

		<div class="d-flex flex-wrap justify-content-center overflow-auto">
			{% for i in range(set_cards|length) %}
			<div
				id="{{ set_cards[i].id }}"
				class="card text-center w-25 mx-5 my-5 align-items-center bg-dark text-white home-set-card set-or-card-badge"
			>
				<div class="card-header">{{ set_cards[i]["name"] }}</div>
				<img
					src="{{ set_cards[i]['images']['small'] }}"
					alt="Pokemon Card"
					class="card-img-top"
				/>
				<div class="card-footer w-100 d-flex justify-content-around">
					<div
						id="{{ set_cards[i]['name'] }}-button-container"
						class="button-status-container"
					>
							{% if set_cards[i].id in grailed_cards %}
							<button class="btn btn-warning btn-lg status-button grailed-button">
								👑
							</button>
							{% elif set_cards[i].id in owned_cards %}
							<button class="btn btn-success btn-lg status-button owned-button">
								✔️
							</button>
							{% else %}
							<button class="btn btn-danger btn-lg status-button not-owned-button">
								❌
							</button>
							{% endif %}
						</button>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}